import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { renderGeneratedArtifacts } from "../src/plugin.ts";

const exampleDir = dirname(new URL(import.meta.url).pathname);
const inputPath = resolve(exampleDir, "openapi.json");
const outputDir = resolve(exampleDir, "output");

mkdirSync(outputDir, { recursive: true });

const spec = JSON.parse(readFileSync(inputPath, "utf-8"));

const artifacts = renderGeneratedArtifacts(spec, {
  httpClient: {
    module: "@example/http",
    jsonFunction: "fetchJson",
    voidFunction: "fetchVoid",
    requestOptionsType: "RequestOptions",
    omitKeys: ["json", "method", "signal"],
  },
});

writeFileSync(resolve(outputDir, "types.ts"), artifacts.types);
writeFileSync(resolve(outputDir, "api.ts"), artifacts.api);
writeFileSync(resolve(outputDir, "client.ts"), artifacts.client);

// Also generate with openapi-typescript for api-types.d.ts
const { default: openapiTS, astToString } = await import("openapi-typescript");
const ast = await openapiTS(new URL(`file://${inputPath}`));
const contents = astToString(ast);
const header = [
  "// This file is auto-generated by vite-plugin-openapi-codegen.",
  "// Do not edit manually. Changes will be overwritten on next build.",
].join("\n");
writeFileSync(resolve(outputDir, "api-types.d.ts"), `${header}\n\n${contents}`);

console.log("Generated 4 files in example/output/:");
console.log("  - api-types.d.ts (OpenAPI TypeScript types)");
console.log("  - types.ts (schema type aliases)");
console.log("  - api.ts (path builder functions)");
console.log("  - client.ts (typed request client)");
