// This file is auto-generated by vite-plugin-openapi-codegen.
// Do not edit manually. Changes will be overwritten on next build.

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health_check"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_users"];
    put?: never;
    post: operations["create_user"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_user"];
    put: operations["update_user"];
    post?: never;
    delete: operations["delete_user"];
    options?: never;
    head?: never;
    patch: operations["patch_user"];
    trace?: never;
  };
  "/api/users/{user_id}/posts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_user_posts"];
    put?: never;
    post: operations["create_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/{user_id}/posts/{post_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_post"];
    put?: never;
    post?: never;
    delete: operations["delete_post"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["search"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/uploads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_upload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/orders/{order_id}/items/{item_id}/review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_item_review"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthResponse: {
      token: string;
      /** Format: date-time */
      expires_at: string;
    };
    CreatePostRequest: {
      title: string;
      body: string;
      tags?: string[];
    };
    CreateUploadRequest: {
      filename: string;
      content_type: string;
      size: number;
    };
    CreateUserRequest: {
      /** Format: email */
      email: string;
      name: string;
      /**
       * @default user
       * @enum {string}
       */
      role: "admin" | "user" | "guest";
    };
    HealthResponse: {
      /** @enum {string} */
      status: "ok" | "degraded";
      version: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    OrderItemReviewPath: {
      order_id: string;
      item_id: string;
    };
    PaginationMeta: {
      page: number;
      per_page: number;
      total: number;
    };
    PatchUserRequest: {
      name?: string;
      /** @enum {string} */
      role?: "admin" | "user" | "guest";
    };
    PostListResponse: {
      items: components["schemas"]["PostResponse"][];
      pagination: components["schemas"]["PaginationMeta"];
    };
    PostResponse: {
      /** Format: uuid */
      id: string;
      title: string;
      body: string;
      /** @enum {string} */
      status: "draft" | "published" | "archived";
      tags?: string[];
      /** Format: date-time */
      created_at: string;
    };
    ReviewRequest: {
      rating: number;
      comment?: string;
    };
    ReviewResponse: {
      /** Format: uuid */
      id: string;
      rating: number;
      comment?: string;
      /** Format: date-time */
      created_at: string;
    };
    SearchResponse: {
      results: {
        type: string;
        id: string;
        title: string;
      }[];
      total: number;
    };
    UpdateUserRequest: {
      /** Format: email */
      email: string;
      name: string;
      /** @enum {string} */
      role?: "admin" | "user" | "guest";
    };
    UploadResponse: {
      /** Format: uuid */
      id: string;
      /** Format: uri */
      url: string;
      /** Format: date-time */
      expires_at: string;
    };
    UserListResponse: {
      items: components["schemas"]["UserResponse"][];
      pagination: components["schemas"]["PaginationMeta"];
    };
    UserPath: {
      /** Format: uuid */
      user_id: string;
    };
    UserPostPath: {
      /** Format: uuid */
      user_id: string;
      /** Format: uuid */
      post_id: string;
    };
    UserResponse: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      name: string;
      /** @enum {string} */
      role: "admin" | "user" | "guest";
      /** Format: date-time */
      created_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Authenticated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logged out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_users: {
    parameters: {
      query: {
        page: number;
        per_page?: number;
        role?: "admin" | "user" | "guest";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserListResponse"];
        };
      };
    };
  };
  create_user: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  get_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  update_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRequest"];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  delete_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  patch_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PatchUserRequest"];
      };
    };
    responses: {
      /** @description Patched */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  list_user_posts: {
    parameters: {
      query?: {
        status?: "draft" | "published" | "archived";
      };
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PostListResponse"];
        };
      };
    };
  };
  create_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePostRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PostResponse"];
        };
      };
    };
  };
  get_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
        post_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PostResponse"];
        };
      };
    };
  };
  delete_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
        post_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  search: {
    parameters: {
      query: {
        q: string;
        type?: "user" | "post" | "all";
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
    };
  };
  create_upload: {
    parameters: {
      query?: {
        notify?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUploadRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadResponse"];
        };
      };
    };
  };
  create_item_review: {
    parameters: {
      query?: {
        draft?: boolean;
      };
      header?: never;
      path: {
        order_id: string;
        item_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviewRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewResponse"];
        };
      };
    };
  };
}
