// This file is auto-generated by vite-plugin-openapi-codegen.
// Do not edit manually. Changes will be overwritten on next build.

import type { OrderItemReviewPath, UserPath, UserPostPath } from "./types";
// Auth
export function postAuthLogin(): string {
  return "auth/login";
}
export function postAuthLogout(): string {
  return "auth/logout";
}
// Health
export function getHealth(): string {
  return "health";
}
// Orders
export function postOrderItemReview(params: OrderItemReviewPath): string {
  return `orders/${params.order_id}/items/${params.item_id}/review`;
}
// Search
export function getSearch(): string {
  return "search";
}
// Uploads
export function postUploads(): string {
  return "uploads";
}
// Users
export function getUsers(): string {
  return "users";
}
export function postUsers(): string {
  return "users";
}
export function getUser(params: UserPath): string {
  return `users/${params.user_id}`;
}
export function putUser(params: UserPath): string {
  return `users/${params.user_id}`;
}
export function deleteUser(params: UserPath): string {
  return `users/${params.user_id}`;
}
export function patchUser(params: UserPath): string {
  return `users/${params.user_id}`;
}
export function getUserPosts(params: UserPath): string {
  return `users/${params.user_id}/posts`;
}
export function postUserPosts(params: UserPath): string {
  return `users/${params.user_id}/posts`;
}
export function getUserPost(params: UserPostPath): string {
  return `users/${params.user_id}/posts/${params.post_id}`;
}
export function deleteUserPost(params: UserPostPath): string {
  return `users/${params.user_id}/posts/${params.post_id}`;
}
