// This file is auto-generated by vite-plugin-openapi-codegen.
// Do not edit manually. Changes will be overwritten on next build.

import type { RequestOptions } from "@example/http";
import { fetchJson, fetchVoid } from "@example/http";
import type { operations } from "./api-types";
import type {
  AuthResponse,
  CreatePostRequest,
  CreateUploadRequest,
  CreateUserRequest,
  HealthResponse,
  LoginRequest,
  OrderItemReviewPath,
  PatchUserRequest,
  PostListResponse,
  PostResponse,
  ReviewRequest,
  ReviewResponse,
  SearchResponse,
  UpdateUserRequest,
  UploadResponse,
  UserListResponse,
  UserPath,
  UserPostPath,
  UserResponse,
} from "./types";
import {
  postAuthLogin as buildPostAuthLoginPath,
  postAuthLogout as buildPostAuthLogoutPath,
  getHealth as buildGetHealthPath,
  postOrderItemReview as buildPostOrderItemReviewPath,
  getSearch as buildGetSearchPath,
  postUploads as buildPostUploadsPath,
  getUsers as buildGetUsersPath,
  postUsers as buildPostUsersPath,
  getUser as buildGetUserPath,
  putUser as buildPutUserPath,
  deleteUser as buildDeleteUserPath,
  patchUser as buildPatchUserPath,
  getUserPosts as buildGetUserPostsPath,
  postUserPosts as buildPostUserPostsPath,
  getUserPost as buildGetUserPostPath,
  deleteUserPost as buildDeleteUserPostPath,
} from "./api";
type RuntimeRequestOptions = Omit<RequestOptions, "json" | "method" | "signal">;
function buildSearchParams(
  query: Record<string, unknown> | undefined,
): URLSearchParams | undefined {
  if (query === undefined) return undefined;
  const entries = Object.entries(query).filter(([, value]) => value != null);
  if (entries.length === 0) return undefined;
  const searchParams = new URLSearchParams();
  for (const [key, value] of entries) {
    searchParams.set(key, String(value));
  }
  return searchParams;
}
// Auth
export interface PostAuthLoginOptions {
  query?: never;
  path?: never;
  body: LoginRequest;
  signal?: AbortSignal;
}
export function postAuthLogin(
  options: PostAuthLoginOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<AuthResponse> {
  return fetchJson<AuthResponse>(buildPostAuthLoginPath(), {
    ...requestOptions,
    method: "POST",
    json: options.body,
    signal: options.signal,
  });
}
export interface PostAuthLogoutOptions {
  query?: never;
  path?: never;
  body?: never;
  signal?: AbortSignal;
}
export function postAuthLogout(
  options: PostAuthLogoutOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<void> {
  return fetchVoid(buildPostAuthLogoutPath(), {
    ...requestOptions,
    method: "POST",
    signal: options.signal,
  });
}
// Health
export interface GetHealthOptions {
  query?: never;
  path?: never;
  body?: never;
  signal?: AbortSignal;
}
export function getHealth(
  options: GetHealthOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<HealthResponse> {
  return fetchJson<HealthResponse>(buildGetHealthPath(), {
    ...requestOptions,
    method: "GET",
    signal: options.signal,
  });
}
// Orders
export interface PostOrderItemReviewOptions {
  query?: operations["create_item_review"]["parameters"]["query"];
  path: OrderItemReviewPath;
  body: ReviewRequest;
  signal?: AbortSignal;
}
export function postOrderItemReview(
  options: PostOrderItemReviewOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<ReviewResponse> {
  return fetchJson<ReviewResponse>(buildPostOrderItemReviewPath(options.path), {
    ...requestOptions,
    method: "POST",
    searchParams: buildSearchParams(options.query),
    json: options.body,
    signal: options.signal,
  });
}
// Search
export interface GetSearchOptions {
  query: operations["search"]["parameters"]["query"];
  path?: never;
  body?: never;
  signal?: AbortSignal;
}
export function getSearch(
  options: GetSearchOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<SearchResponse> {
  return fetchJson<SearchResponse>(buildGetSearchPath(), {
    ...requestOptions,
    method: "GET",
    searchParams: buildSearchParams(options.query),
    signal: options.signal,
  });
}
// Uploads
export interface PostUploadsOptions {
  query?: operations["create_upload"]["parameters"]["query"];
  path?: never;
  body: CreateUploadRequest;
  signal?: AbortSignal;
}
export function postUploads(
  options: PostUploadsOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<UploadResponse> {
  return fetchJson<UploadResponse>(buildPostUploadsPath(), {
    ...requestOptions,
    method: "POST",
    searchParams: buildSearchParams(options.query),
    json: options.body,
    signal: options.signal,
  });
}
// Users
export interface GetUsersOptions {
  query: operations["list_users"]["parameters"]["query"];
  path?: never;
  body?: never;
  signal?: AbortSignal;
}
export function getUsers(
  options: GetUsersOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<UserListResponse> {
  return fetchJson<UserListResponse>(buildGetUsersPath(), {
    ...requestOptions,
    method: "GET",
    searchParams: buildSearchParams(options.query),
    signal: options.signal,
  });
}
export interface PostUsersOptions {
  query?: never;
  path?: never;
  body: CreateUserRequest;
  signal?: AbortSignal;
}
export function postUsers(
  options: PostUsersOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<UserResponse> {
  return fetchJson<UserResponse>(buildPostUsersPath(), {
    ...requestOptions,
    method: "POST",
    json: options.body,
    signal: options.signal,
  });
}
export interface GetUserOptions {
  query?: never;
  path: UserPath;
  body?: never;
  signal?: AbortSignal;
}
export function getUser(
  options: GetUserOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<UserResponse> {
  return fetchJson<UserResponse>(buildGetUserPath(options.path), {
    ...requestOptions,
    method: "GET",
    signal: options.signal,
  });
}
export interface PutUserOptions {
  query?: never;
  path: UserPath;
  body: UpdateUserRequest;
  signal?: AbortSignal;
}
export function putUser(
  options: PutUserOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<UserResponse> {
  return fetchJson<UserResponse>(buildPutUserPath(options.path), {
    ...requestOptions,
    method: "PUT",
    json: options.body,
    signal: options.signal,
  });
}
export interface DeleteUserOptions {
  query?: never;
  path: UserPath;
  body?: never;
  signal?: AbortSignal;
}
export function deleteUser(
  options: DeleteUserOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<void> {
  return fetchVoid(buildDeleteUserPath(options.path), {
    ...requestOptions,
    method: "DELETE",
    signal: options.signal,
  });
}
export interface PatchUserOptions {
  query?: never;
  path: UserPath;
  body: PatchUserRequest;
  signal?: AbortSignal;
}
export function patchUser(
  options: PatchUserOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<UserResponse> {
  return fetchJson<UserResponse>(buildPatchUserPath(options.path), {
    ...requestOptions,
    method: "PATCH",
    json: options.body,
    signal: options.signal,
  });
}
export interface GetUserPostsOptions {
  query?: operations["list_user_posts"]["parameters"]["query"];
  path: UserPath;
  body?: never;
  signal?: AbortSignal;
}
export function getUserPosts(
  options: GetUserPostsOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<PostListResponse> {
  return fetchJson<PostListResponse>(buildGetUserPostsPath(options.path), {
    ...requestOptions,
    method: "GET",
    searchParams: buildSearchParams(options.query),
    signal: options.signal,
  });
}
export interface PostUserPostsOptions {
  query?: never;
  path: UserPath;
  body: CreatePostRequest;
  signal?: AbortSignal;
}
export function postUserPosts(
  options: PostUserPostsOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<PostResponse> {
  return fetchJson<PostResponse>(buildPostUserPostsPath(options.path), {
    ...requestOptions,
    method: "POST",
    json: options.body,
    signal: options.signal,
  });
}
export interface GetUserPostOptions {
  query?: never;
  path: UserPostPath;
  body?: never;
  signal?: AbortSignal;
}
export function getUserPost(
  options: GetUserPostOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<PostResponse> {
  return fetchJson<PostResponse>(buildGetUserPostPath(options.path), {
    ...requestOptions,
    method: "GET",
    signal: options.signal,
  });
}
export interface DeleteUserPostOptions {
  query?: never;
  path: UserPostPath;
  body?: never;
  signal?: AbortSignal;
}
export function deleteUserPost(
  options: DeleteUserPostOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<void> {
  return fetchVoid(buildDeleteUserPostPath(options.path), {
    ...requestOptions,
    method: "DELETE",
    signal: options.signal,
  });
}
