// This file is auto-generated by vite-plugin-openapi-codegen.
// Do not edit manually. Changes will be overwritten on next build.

import type { components } from "./api-types";
export type AuthResponse = components["schemas"]["AuthResponse"];
export type CreatePostRequest = components["schemas"]["CreatePostRequest"];
export type CreateUploadRequest = components["schemas"]["CreateUploadRequest"];
export type CreateUserRequest = components["schemas"]["CreateUserRequest"];
export type HealthResponse = components["schemas"]["HealthResponse"];
export type LoginRequest = components["schemas"]["LoginRequest"];
export type OrderItemReviewPath = components["schemas"]["OrderItemReviewPath"];
export type PaginationMeta = components["schemas"]["PaginationMeta"];
export type PatchUserRequest = components["schemas"]["PatchUserRequest"];
export type PostListResponse = components["schemas"]["PostListResponse"];
export type PostResponse = components["schemas"]["PostResponse"];
export type ReviewRequest = components["schemas"]["ReviewRequest"];
export type ReviewResponse = components["schemas"]["ReviewResponse"];
export type SearchResponse = components["schemas"]["SearchResponse"];
export type UpdateUserRequest = components["schemas"]["UpdateUserRequest"];
export type UploadResponse = components["schemas"]["UploadResponse"];
export type UserListResponse = components["schemas"]["UserListResponse"];
export type UserPath = components["schemas"]["UserPath"];
export type UserPostPath = components["schemas"]["UserPostPath"];
export type UserResponse = components["schemas"]["UserResponse"];
