import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

import type { Plugin, ResolvedConfig } from "vite-plus";
import { parse as parseYaml } from "yaml";

import { renderApiSource, renderClientSource, renderOperationTypeAliases } from "./ast.ts";
import type {
  NormalizedChannel,
  NormalizedTypeReference,
  OpenAPISpec,
  OperationEntry,
  TypeAliasDefinition,
} from "./normalization.ts";
import {
  buildClientRenderModelFromOperations,
  collectOperations,
  warnOnParameterLocationMismatch,
} from "./normalization.ts";

export interface HttpClientConfig {
  /** HTTP module import path. Default: '#/integrations/http' */
  module?: string;
  /** Function name for JSON-returning requests. Default: 'requestJson' */
  jsonFunction?: string;
  /** Function name for void requests. Default: 'requestVoid' */
  voidFunction?: string;
  /** Type name for request options (type-only import). Default: 'ApiRequestOptions' */
  requestOptionsType?: string;
  /** Keys to Omit from requestOptionsType for RuntimeRequestOptions. Default: ['json','method','searchParams','signal'] */
  omitKeys?: string[];
}

const HTTP_CLIENT_DEFAULTS: Required<HttpClientConfig> = {
  module: "#/integrations/http",
  jsonFunction: "requestJson",
  voidFunction: "requestVoid",
  requestOptionsType: "ApiRequestOptions",
  omitKeys: ["json", "method", "searchParams", "signal"],
};

function resolveHttpClientConfig(config?: HttpClientConfig): Required<HttpClientConfig> {
  return { ...HTTP_CLIENT_DEFAULTS, ...config };
}

export interface Options {
  /** Path or HTTP(S) URL to an OpenAPI JSON/YAML document */
  input: string;
  /** Output directory for generated files (relative to project root) */
  output: string;
  /** Path prefix for filtering and stripping. Default: '/api/' */
  pathPrefix?: string;
  /** Whether to strip pathPrefix from generated paths. Default: true */
  stripPrefix?: boolean;
  /** HTTP client configuration */
  httpClient?: HttpClientConfig;
  /** Generate and consume top-level type aliases. Default: false */
  typeAliases?: boolean;
  /** Whether to generate during Vite dev server startup. Default: true */
  generateOnDev?: boolean;
  /** Whether to regenerate through Vite HMR for local inputs. Default: true */
  generateOnHmr?: boolean;
}

const GENERATED_HEADER = [
  "// This file is auto-generated by vite-plugin-openapi-codegen.",
  "// Do not edit manually. Changes will be overwritten on next build.",
];

interface GeneratedArtifacts {
  api: string;
  apiTypes?: string;
  client: string;
}

interface LoadedOpenAPIInput {
  apiTypesSource: string | URL;
  spec: OpenAPISpec;
}

async function generateApiTypes(
  source: string | URL,
  outputDir: string,
  useTypeAliases: boolean,
): Promise<void> {
  const { default: openapiTS, astToString } = await import("openapi-typescript");
  const ast = await openapiTS(
    source,
    useTypeAliases
      ? {
          rootTypes: true,
          rootTypesKeepCasing: true,
          rootTypesNoSchemaPrefix: true,
        }
      : undefined,
  );
  const contents = astToString(ast);
  writeFileSync(
    resolve(outputDir, "api-types.d.ts"),
    `${GENERATED_HEADER.join("\n")}\n\n${contents}`,
  );
}

function createApiEntries(
  normalizedOps: Array<{
    bodyContentType: "json" | "binary" | "formData" | null;
    entry: { funcName: string; group: string; strippedPath: string };
    pathChannel: NormalizedChannel;
  }>,
  useTypeAliases: boolean,
) {
  return normalizedOps.map((op) => ({
    funcName: op.entry.funcName,
    group: op.entry.group,
    bodyContentType: op.bodyContentType,
    pathTypeExpr:
      op.pathChannel.typeRef == null
        ? null
        : useTypeAliases
          ? op.pathChannel.typeRef.typeName
          : op.pathChannel.typeRef.sourceExpr,
    strippedPath: op.entry.strippedPath,
  }));
}

function createClientRenderModel(
  model: {
    needsSearchParamsHelper: boolean;
    operations: Array<{
      bodyChannel: NormalizedChannel;
      bodyContentType: "json" | "binary" | "formData" | null;
      builderAlias: string;
      entry: { funcName: string; group: string; method: string };
      optionTypeName: string;
      pathChannel: NormalizedChannel;
      pathInvocationExpr: string;
      queryChannel: NormalizedChannel;
      requestFunction: string;
      responseTypeRef: NormalizedTypeReference | null;
      returnTypeExpr: string;
    }>;
    typeAliases: TypeAliasDefinition[];
  },
  useTypeAliases: boolean,
) {
  const resolveTypeExpr = (typeRef: NormalizedTypeReference | null) =>
    typeRef == null ? null : useTypeAliases ? typeRef.typeName : typeRef.sourceExpr;

  const resolveReturnTypeExpr = (operation: {
    responseTypeRef: NormalizedTypeReference | null;
  }) => {
    const responseTypeExpr = resolveTypeExpr(operation.responseTypeRef);
    return responseTypeExpr ? `Promise<${responseTypeExpr}>` : "Promise<void>";
  };

  return {
    needsSearchParamsHelper: model.needsSearchParamsHelper,
    operations: model.operations.map((operation) => ({
      bodyChannel: resolveChannel(operation.bodyChannel, useTypeAliases),
      bodyContentType: operation.bodyContentType,
      builderAlias: operation.builderAlias,
      funcName: operation.entry.funcName,
      group: operation.entry.group,
      methodUpper: operation.entry.method.toUpperCase(),
      optionTypeName: operation.optionTypeName,
      pathChannel: resolveChannel(operation.pathChannel, useTypeAliases),
      pathInvocationExpr: operation.pathInvocationExpr,
      queryChannel: resolveChannel(operation.queryChannel, useTypeAliases),
      requestFunction: operation.requestFunction,
      responseTypeExpr: resolveTypeExpr(operation.responseTypeRef),
      returnTypeExpr: resolveReturnTypeExpr(operation),
    })),
  };
}

function resolveChannel(channel: NormalizedChannel, useTypeAliases: boolean): NormalizedChannel {
  if (!channel.typeRef) {
    return channel;
  }

  return {
    ...channel,
    typeRef: {
      ...channel.typeRef,
      sourceExpr: useTypeAliases ? channel.typeRef.typeName : channel.typeRef.sourceExpr,
    },
  };
}

export function renderGeneratedArtifacts(
  spec: OpenAPISpec,
  options: Pick<Options, "httpClient" | "pathPrefix" | "stripPrefix" | "typeAliases">,
  preCollectedOperations?: OperationEntry[],
): GeneratedArtifacts {
  const pathPrefix = options.pathPrefix ?? "/api/";
  const stripPrefix = options.stripPrefix ?? true;
  const httpClient = resolveHttpClientConfig(options.httpClient);
  const useTypeAliases = options.typeAliases ?? false;
  const operations = preCollectedOperations ?? collectOperations(spec, pathPrefix, stripPrefix);
  const clientModel = buildClientRenderModelFromOperations(operations, spec, {
    json: httpClient.jsonFunction,
    void: httpClient.voidFunction,
  });
  if (clientModel.operations.length === 0) {
    throw new Error(`No paths matching prefix "${pathPrefix}" found in openapi.json`);
  }

  return {
    api: renderApiSource(
      createApiEntries(clientModel.operations, useTypeAliases),
      GENERATED_HEADER,
    ),
    client: renderClientSource(
      createClientRenderModel(clientModel, useTypeAliases),
      GENERATED_HEADER,
      httpClient,
    ),
    ...(useTypeAliases && clientModel.typeAliases.length > 0
      ? { apiTypes: renderOperationTypeAliases(clientModel.typeAliases) }
      : {}),
  };
}

async function loadOpenAPIInput(root: string, input: string): Promise<LoadedOpenAPIInput> {
  if (isHttpUrl(input)) {
    const sourceText = await fetchRemoteOpenAPIInput(input);

    return {
      apiTypesSource: sourceText,
      spec: parseOpenAPISpec(sourceText, input),
    };
  }

  const inputPath = resolve(root, input);
  const sourceText = readFileSync(inputPath, "utf-8");

  return {
    apiTypesSource: pathToFileURL(inputPath),
    spec: parseOpenAPISpec(sourceText, inputPath),
  };
}

function isHttpUrl(value: string): boolean {
  try {
    const url = new URL(value);
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
}

async function fetchRemoteOpenAPIInput(input: string): Promise<string> {
  const response = await fetch(input);
  if (!response.ok) {
    throw new Error(
      `[openapi-codegen] Failed to fetch OpenAPI document from ${input}: ${response.status} ${response.statusText}`,
    );
  }

  return response.text();
}

function parseOpenAPISpec(sourceText: string, inputLabel: string): OpenAPISpec {
  const parsed = parseYaml(sourceText);
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(`[openapi-codegen] Expected OpenAPI document object from ${inputLabel}`);
  }

  return parsed as OpenAPISpec;
}

export async function generateOpenAPIArtifacts(root: string, options: Options): Promise<void> {
  const outputDir = resolve(root, options.output);
  mkdirSync(outputDir, { recursive: true });
  const { apiTypesSource, spec } = await loadOpenAPIInput(root, options.input);
  const pathPrefix = options.pathPrefix ?? "/api/";
  const stripPrefix = options.stripPrefix ?? true;
  const operations = collectOperations(spec, pathPrefix, stripPrefix);
  const artifacts = renderGeneratedArtifacts(spec, options, operations);

  warnOnParameterLocationMismatch(operations);
  await generateApiTypes(apiTypesSource, outputDir, options.typeAliases ?? false);
  if (artifacts.apiTypes) {
    writeFileSync(resolve(outputDir, "api-types.d.ts"), artifacts.apiTypes, { flag: "a" });
  }
  writeFileSync(resolve(outputDir, "api.ts"), artifacts.api);
  writeFileSync(resolve(outputDir, "client.ts"), artifacts.client);
}

export function openapiCodegen(options: Options): Plugin {
  let root = process.cwd();
  let command: ResolvedConfig["command"] = "build";

  return {
    name: "openapi-codegen",
    enforce: "pre",
    api: {
      options,
    },

    configResolved(config: ResolvedConfig) {
      root = config.root;
      command = config.command;
    },

    async buildStart() {
      if (command === "serve" && options.generateOnDev !== false) {
        void runDevelopmentGeneration(root, options);
        return;
      }

      return;
    },

    async handleHotUpdate(ctx) {
      if (options.generateOnHmr === false) {
        return;
      }

      if (isHttpUrl(options.input)) {
        return;
      }

      const inputPath = resolve(root, options.input);
      if (resolve(ctx.file) !== inputPath) {
        return;
      }

      console.log("[openapi-codegen] openapi.json changed, regenerating...");
      await runDevelopmentGeneration(root, options, {
        onSuccess: () => {
          console.log("[openapi-codegen] regeneration complete.");
        },
      });
    },
  };
}

async function runDevelopmentGeneration(
  root: string,
  options: Options,
  handlers?: { onSuccess?: () => void },
): Promise<void> {
  try {
    await generateOpenAPIArtifacts(root, options);
    handlers?.onSuccess?.();
  } catch (error) {
    console.error("[openapi-codegen] generation failed during dev mode.", error);
  }
}
