import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import type { Plugin, ResolvedConfig } from "vite-plus";

import { renderApiSource, renderClientSource, renderTypesSource } from "./ast.ts";
import type { NormalizedChannel, OpenAPISpec, OperationEntry } from "./normalization.ts";
import {
  buildClientRenderModelFromOperations,
  collectOperations,
  warnOnParameterLocationMismatch,
} from "./normalization.ts";

export interface HttpClientConfig {
  /** HTTP module import path. Default: '#/integrations/http' */
  module?: string;
  /** Function name for JSON-returning requests. Default: 'requestJson' */
  jsonFunction?: string;
  /** Function name for void requests. Default: 'requestVoid' */
  voidFunction?: string;
  /** Type name for request options (type-only import). Default: 'ApiRequestOptions' */
  requestOptionsType?: string;
  /** Keys to Omit from requestOptionsType for RuntimeRequestOptions. Default: ['json','method','searchParams','signal'] */
  omitKeys?: string[];
}

const HTTP_CLIENT_DEFAULTS: Required<HttpClientConfig> = {
  module: "#/integrations/http",
  jsonFunction: "requestJson",
  voidFunction: "requestVoid",
  requestOptionsType: "ApiRequestOptions",
  omitKeys: ["json", "method", "searchParams", "signal"],
};

function resolveHttpClientConfig(config?: HttpClientConfig): Required<HttpClientConfig> {
  return { ...HTTP_CLIENT_DEFAULTS, ...config };
}

export interface Options {
  /** Path to openapi.json (relative to project root) */
  input: string;
  /** Output directory for generated files (relative to project root) */
  output: string;
  /** Path prefix for filtering and stripping. Default: '/api/' */
  pathPrefix?: string;
  /** Whether to strip pathPrefix from generated paths. Default: true */
  stripPrefix?: boolean;
  /** HTTP client configuration */
  httpClient?: HttpClientConfig;
  /** Legacy type aliases for types.ts: { OldName: 'NewName' } */
  legacyAliases?: Record<string, string>;
}

const GENERATED_HEADER = [
  "// This file is auto-generated by vite-plugin-openapi-codegen.",
  "// Do not edit manually. Changes will be overwritten on next build.",
];

interface GeneratedArtifacts {
  api: string;
  client: string;
  types: string;
}

async function generateApiTypes(inputPath: string, outputDir: string): Promise<void> {
  const { default: openapiTS, astToString } = await import("openapi-typescript");
  const ast = await openapiTS(new URL(`file://${inputPath}`));
  const contents = astToString(ast);
  writeFileSync(
    resolve(outputDir, "api-types.d.ts"),
    `${GENERATED_HEADER.join("\n")}\n\n${contents}`,
  );
}

function renderTypesBarrel(spec: OpenAPISpec, legacyAliases?: Record<string, string>): string {
  const schemaNames = Object.keys(spec.components?.schemas ?? {}).sort();
  if (schemaNames.length === 0) {
    throw new Error("No schemas found in openapi.json");
  }

  return renderTypesSource(schemaNames, legacyAliases, GENERATED_HEADER);
}

function createApiEntries(
  normalizedOps: Array<{
    entry: { funcName: string; group: string; strippedPath: string };
    pathChannel: NormalizedChannel;
  }>,
) {
  return normalizedOps.map((op) => ({
    funcName: op.entry.funcName,
    group: op.entry.group,
    pathTypeExpr: op.pathChannel.present ? op.pathChannel.typeExpr : null,
    strippedPath: op.entry.strippedPath,
  }));
}

function createClientRenderModel(model: {
  needsSearchParamsHelper: boolean;
  operations: Array<{
    bodyChannel: NormalizedChannel;
    builderAlias: string;
    entry: { funcName: string; group: string; method: string };
    optionTypeName: string;
    pathChannel: NormalizedChannel;
    pathInvocationExpr: string;
    queryChannel: NormalizedChannel;
    requestFunction: string;
    responseTypeExpr: string | null;
    returnTypeExpr: string;
  }>;
  typeImports: string[];
}) {
  return {
    needsSearchParamsHelper: model.needsSearchParamsHelper,
    operations: model.operations.map((operation) => ({
      bodyChannel: operation.bodyChannel,
      builderAlias: operation.builderAlias,
      funcName: operation.entry.funcName,
      group: operation.entry.group,
      methodUpper: operation.entry.method.toUpperCase(),
      optionTypeName: operation.optionTypeName,
      pathChannel: operation.pathChannel,
      pathInvocationExpr: operation.pathInvocationExpr,
      queryChannel: operation.queryChannel,
      requestFunction: operation.requestFunction,
      responseTypeExpr: operation.responseTypeExpr,
      returnTypeExpr: operation.returnTypeExpr,
    })),
    typeImports: model.typeImports,
  };
}

export function renderGeneratedArtifacts(
  spec: OpenAPISpec,
  options: Pick<Options, "httpClient" | "legacyAliases" | "pathPrefix" | "stripPrefix">,
  preCollectedOperations?: OperationEntry[],
): GeneratedArtifacts {
  const pathPrefix = options.pathPrefix ?? "/api/";
  const stripPrefix = options.stripPrefix ?? true;
  const httpClient = resolveHttpClientConfig(options.httpClient);
  const operations = preCollectedOperations ?? collectOperations(spec, pathPrefix, stripPrefix);
  const clientModel = buildClientRenderModelFromOperations(operations, spec, {
    json: httpClient.jsonFunction,
    void: httpClient.voidFunction,
  });
  if (clientModel.operations.length === 0) {
    throw new Error(`No paths matching prefix "${pathPrefix}" found in openapi.json`);
  }

  return {
    api: renderApiSource(createApiEntries(clientModel.operations), GENERATED_HEADER),
    client: renderClientSource(createClientRenderModel(clientModel), GENERATED_HEADER, httpClient),
    types: renderTypesBarrel(spec, options.legacyAliases),
  };
}

async function generate(root: string, options: Options): Promise<void> {
  const inputPath = resolve(root, options.input);
  const outputDir = resolve(root, options.output);
  const spec = JSON.parse(readFileSync(inputPath, "utf-8")) as OpenAPISpec;
  const pathPrefix = options.pathPrefix ?? "/api/";
  const stripPrefix = options.stripPrefix ?? true;
  const operations = collectOperations(spec, pathPrefix, stripPrefix);
  const artifacts = renderGeneratedArtifacts(spec, options, operations);

  warnOnParameterLocationMismatch(operations);
  await generateApiTypes(inputPath, outputDir);
  writeFileSync(resolve(outputDir, "types.ts"), artifacts.types);
  writeFileSync(resolve(outputDir, "api.ts"), artifacts.api);
  writeFileSync(resolve(outputDir, "client.ts"), artifacts.client);
}

export function openapiCodegen(options: Options): Plugin {
  let root = process.cwd();

  return {
    name: "openapi-codegen",
    enforce: "pre",

    configResolved(config: ResolvedConfig) {
      root = config.root;
    },

    async buildStart() {
      await generate(root, options);
    },

    configureServer(server) {
      const inputPath = resolve(root, options.input);

      server.watcher.add(inputPath);
      server.watcher.on("change", async (path) => {
        if (path === inputPath) {
          console.log("[openapi-codegen] openapi.json changed, regenerating...");
          await generate(root, options);
          console.log("[openapi-codegen] regeneration complete.");
        }
      });
    },
  };
}
