import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

import type { Plugin, ResolvedConfig } from "vite-plus";
import { parse as parseYaml } from "yaml";

import { renderApiSource, renderClientSource } from "./ast.ts";
import type { NormalizedChannel, OpenAPISpec, OperationEntry } from "./normalization.ts";
import {
  buildClientRenderModelFromOperations,
  collectOperations,
  warnOnParameterLocationMismatch,
} from "./normalization.ts";

export interface HttpClientConfig {
  /** HTTP module import path. Default: '#/integrations/http' */
  module?: string;
  /** Function name for JSON-returning requests. Default: 'requestJson' */
  jsonFunction?: string;
  /** Function name for void requests. Default: 'requestVoid' */
  voidFunction?: string;
  /** Type name for request options (type-only import). Default: 'ApiRequestOptions' */
  requestOptionsType?: string;
  /** Keys to Omit from requestOptionsType for RuntimeRequestOptions. Default: ['json','method','searchParams','signal'] */
  omitKeys?: string[];
}

const HTTP_CLIENT_DEFAULTS: Required<HttpClientConfig> = {
  module: "#/integrations/http",
  jsonFunction: "requestJson",
  voidFunction: "requestVoid",
  requestOptionsType: "ApiRequestOptions",
  omitKeys: ["json", "method", "searchParams", "signal"],
};

function resolveHttpClientConfig(config?: HttpClientConfig): Required<HttpClientConfig> {
  return { ...HTTP_CLIENT_DEFAULTS, ...config };
}

export interface Options {
  /** Path or HTTP(S) URL to an OpenAPI JSON/YAML document */
  input: string;
  /** Output directory for generated files (relative to project root) */
  output: string;
  /** Path prefix for filtering and stripping. Default: '/api/' */
  pathPrefix?: string;
  /** Whether to strip pathPrefix from generated paths. Default: true */
  stripPrefix?: boolean;
  /** HTTP client configuration */
  httpClient?: HttpClientConfig;
}

const GENERATED_HEADER = [
  "// This file is auto-generated by vite-plugin-openapi-codegen.",
  "// Do not edit manually. Changes will be overwritten on next build.",
];

interface GeneratedArtifacts {
  api: string;
  client: string;
}

interface LoadedOpenAPIInput {
  apiTypesSource: string | URL;
  spec: OpenAPISpec;
}

async function generateApiTypes(source: string | URL, outputDir: string): Promise<void> {
  const { default: openapiTS, astToString } = await import("openapi-typescript");
  const ast = await openapiTS(source);
  const contents = astToString(ast);
  writeFileSync(
    resolve(outputDir, "api-types.d.ts"),
    `${GENERATED_HEADER.join("\n")}\n\n${contents}`,
  );
}

function createApiEntries(
  normalizedOps: Array<{
    entry: { funcName: string; group: string; strippedPath: string };
    pathChannel: NormalizedChannel;
  }>,
) {
  return normalizedOps.map((op) => ({
    funcName: op.entry.funcName,
    group: op.entry.group,
    pathTypeExpr: op.pathChannel.present ? op.pathChannel.typeExpr : null,
    strippedPath: op.entry.strippedPath,
  }));
}

function createClientRenderModel(model: {
  needsSearchParamsHelper: boolean;
  operations: Array<{
    bodyChannel: NormalizedChannel;
    builderAlias: string;
    entry: { funcName: string; group: string; method: string };
    optionTypeName: string;
    pathChannel: NormalizedChannel;
    pathInvocationExpr: string;
    queryChannel: NormalizedChannel;
    requestFunction: string;
    responseTypeExpr: string | null;
    returnTypeExpr: string;
  }>;
}) {
  return {
    needsSearchParamsHelper: model.needsSearchParamsHelper,
    operations: model.operations.map((operation) => ({
      bodyChannel: operation.bodyChannel,
      builderAlias: operation.builderAlias,
      funcName: operation.entry.funcName,
      group: operation.entry.group,
      methodUpper: operation.entry.method.toUpperCase(),
      optionTypeName: operation.optionTypeName,
      pathChannel: operation.pathChannel,
      pathInvocationExpr: operation.pathInvocationExpr,
      queryChannel: operation.queryChannel,
      requestFunction: operation.requestFunction,
      responseTypeExpr: operation.responseTypeExpr,
      returnTypeExpr: operation.returnTypeExpr,
    })),
  };
}

export function renderGeneratedArtifacts(
  spec: OpenAPISpec,
  options: Pick<Options, "httpClient" | "pathPrefix" | "stripPrefix">,
  preCollectedOperations?: OperationEntry[],
): GeneratedArtifacts {
  const pathPrefix = options.pathPrefix ?? "/api/";
  const stripPrefix = options.stripPrefix ?? true;
  const httpClient = resolveHttpClientConfig(options.httpClient);
  const operations = preCollectedOperations ?? collectOperations(spec, pathPrefix, stripPrefix);
  const clientModel = buildClientRenderModelFromOperations(operations, spec, {
    json: httpClient.jsonFunction,
    void: httpClient.voidFunction,
  });
  if (clientModel.operations.length === 0) {
    throw new Error(`No paths matching prefix "${pathPrefix}" found in openapi.json`);
  }

  return {
    api: renderApiSource(createApiEntries(clientModel.operations), GENERATED_HEADER),
    client: renderClientSource(createClientRenderModel(clientModel), GENERATED_HEADER, httpClient),
  };
}

async function loadOpenAPIInput(root: string, input: string): Promise<LoadedOpenAPIInput> {
  if (isHttpUrl(input)) {
    const sourceText = await fetchRemoteOpenAPIInput(input);

    return {
      apiTypesSource: sourceText,
      spec: parseOpenAPISpec(sourceText, input),
    };
  }

  const inputPath = resolve(root, input);
  const sourceText = readFileSync(inputPath, "utf-8");

  return {
    apiTypesSource: pathToFileURL(inputPath),
    spec: parseOpenAPISpec(sourceText, inputPath),
  };
}

function isHttpUrl(value: string): boolean {
  try {
    const url = new URL(value);
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
}

async function fetchRemoteOpenAPIInput(input: string): Promise<string> {
  const response = await fetch(input);
  if (!response.ok) {
    throw new Error(
      `[openapi-codegen] Failed to fetch OpenAPI document from ${input}: ${response.status} ${response.statusText}`,
    );
  }

  return response.text();
}

function parseOpenAPISpec(sourceText: string, inputLabel: string): OpenAPISpec {
  const parsed = parseYaml(sourceText);
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(`[openapi-codegen] Expected OpenAPI document object from ${inputLabel}`);
  }

  return parsed as OpenAPISpec;
}

async function generate(root: string, options: Options): Promise<void> {
  const outputDir = resolve(root, options.output);
  mkdirSync(outputDir, { recursive: true });
  const { apiTypesSource, spec } = await loadOpenAPIInput(root, options.input);
  const pathPrefix = options.pathPrefix ?? "/api/";
  const stripPrefix = options.stripPrefix ?? true;
  const operations = collectOperations(spec, pathPrefix, stripPrefix);
  const artifacts = renderGeneratedArtifacts(spec, options, operations);

  warnOnParameterLocationMismatch(operations);
  await generateApiTypes(apiTypesSource, outputDir);
  writeFileSync(resolve(outputDir, "api.ts"), artifacts.api);
  writeFileSync(resolve(outputDir, "client.ts"), artifacts.client);
}

export function openapiCodegen(options: Options): Plugin {
  let root = process.cwd();
  let command: ResolvedConfig["command"] = "build";

  return {
    name: "openapi-codegen",
    enforce: "pre",

    configResolved(config: ResolvedConfig) {
      root = config.root;
      command = config.command;
    },

    async buildStart() {
      if (command === "serve") {
        void runDevelopmentGeneration(root, options);
        return;
      }

      return;
    },

    configureServer(server) {
      if (isHttpUrl(options.input)) {
        return;
      }

      const inputPath = resolve(root, options.input);

      server.watcher.add(inputPath);
      server.watcher.on("change", async (path) => {
        if (path === inputPath) {
          console.log("[openapi-codegen] openapi.json changed, regenerating...");
          void runDevelopmentGeneration(root, options, {
            onSuccess: () => {
              console.log("[openapi-codegen] regeneration complete.");
            },
          });
        }
      });
    },
  };
}

async function runDevelopmentGeneration(
  root: string,
  options: Options,
  handlers?: { onSuccess?: () => void },
): Promise<void> {
  try {
    await generate(root, options);
    handlers?.onSuccess?.();
  } catch (error) {
    console.error("[openapi-codegen] generation failed during dev mode.", error);
  }
}
